cursor            #b5d086
cursor_text_color #233600

foreground            #e3e3d8
background            #0d0f09
selection_foreground  #2b331d
selection_background  #c1caab
url_color             #c1caab

#: black 000000 767676
color0  #12140e
color8  #33362e
#: red cc0403 f2201f
color1  #32302c
color9  #837f74
#: green 19cb00 23fd00
color2  #c1caab
color10 #dde6c6
#: yellow cecb00 fffd00
color3  #a0d0c9
color11 #bcece5
#: blue 0d73cc 1a8fff
color4  #384d12
color12 #b5d086
#: magenta cb1ed1 fd28ff
color5  #414a32
color13 #c1caab
#: cyan 0dcdcd 14ffff
color6  #1f4e4a
color14 #a0d0c9
#: white dddddd ffffff
color7  #c5c8b9
color15 #e3e3d8

mark1_foreground #131f00
mark1_background #d1eca0
mark2_foreground #171e0a
mark2_background #dde6c6
mark3_foreground #00201d
mark3_background #bcece5

active_tab_foreground #233600
active_tab_background #b5d086
inactive_tab_foreground #d1eca0
inactive_tab_background #384d12

active_border_color #b5d086
inactive_border_color #233600
# bell_border_color #ff5a00
