# ~/.config/matugen/config.toml

[config]
# Можно оставить пустым, Matugen сам подберет лучшие настройки
# Или добавь это, чтобы цвета были "сочнее":
backend = "matugen" 
palette = "vibrant"

# Правильный конфиг для Matugen
[templates.waybar]
input_path = "~/.config/matugen/templates/waybar.css"
output_path = "~/.cache/matugen/waybar.css"
post_hook = "killall -SIGUSR2 waybar"

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/themes/Matugen.conf'
post_hook = "kitty +kitten themes --reload-in=all Matugen"

[templates.niri]
input_path = '~/.config/matugen/templates/niri-colors.kdl'
output_path = '~/.config/niri/colors.kdl'
post_hook = 'niri msg action load-config-file'

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.rofi]
input_path = './templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.qt5ct]
input_path = './templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = './templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'
# ...

[templates.kde_colors]
input_path = '~/.config/matugen/templates/kde.colors'
output_path = '~/.local/share/color-schemes/Matugen.colors'
#post_cmd = 'plasma-apply-colorscheme Matugen'
#[templates.firefox-website-colors]
#input_path = "path/to/template/"
#output_path = "~/path/to/profile/chrome/colors.css"╭─[ kde_colors:5:20 ]
#[templates.fuzzel]
#input_path = './templates/fuzzel.ini'
#output_path = '~/.config/fuzzel/colors.ini'

#[templates.walker]
#input_path = "~/.config/matugen/templates/walker.css"
#output_path = "~/.cache/matugen/walker.css"
#post_hook = "killall -SIGUSR2 walker"
